project:
  type: website
  output-dir: docs

website:
  title: "All U Need"
  site-url: https://tchken.github.io
  navbar:
    left:
      - text: Home
        href: index.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



