project:
  type: website
  output-dir: docs

website:
  title: "All U Need"
  site-url: https://tchk.com
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog.html
      - about.qmd

format:
  html:
    theme: [sandstone, theme.scss]
    css: styles.css
    toc: true

collections:
    posts:
        authors_metadata: false


