project:
  type: website
  output-dir: docs

website:
  title: "All U Need"
  site-url: https://tchken.github.io
  description: "This is All YOU Need"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog.html
    right:
      - about.qmd

format:
  html:
    theme: [yeti, theme.scss]
    css: styles.css
    toc: true

collections:
    posts:
        authors_metadata: false


